# Generated by Django 5.1.1 on 2024-09-22 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='borrowed_books',
        ),
        migrations.AddField(
            model_name='user',
            name='borrowed_books',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_library.book'),
        ),
    ]
